### ISSUE TITLE
No atom/rss feed

### ISSUE THREAD

**Issue by Skyr** [rusticus-io/website#3]
A feed of some kind (atom/rss) would be awesome! I know, I seem to belong to a dying species, but I follow all webpages of interest via an RSS reader - I don't like checking dozens of bookmarks to see if there are some updates...

**Comment by matthiasbeyer** [comment]
I second this. RSS would be really great!

**Comment by thinkrapido** [comment]
who wants to create rss feed templates?

**Comment by matthiasbeyer** [comment]
No need to, this site gets build with hugo, afaik that already creates rss, right?

**Comment by thinkrapido** [comment]
I added a rss feed template.
Locations: http://rusticus.io/<path>/index.xml
